### ISSUE TITLE
Error When Creating Tests With New Names (Singularity)

### ISSUE THREAD

**Issue by Snell1224** [ovis-hpc/ldms-test#12]
Received a "cluster not found" type error when trying to create and run a new test name. 
Below are two images of the debug logging output in runtime/singularity.py and the new test "agg_test_sw".
 
![image](https://user-images.githubusercontent.com/60634446/121933085-dd381180-cd02-11eb-918b-6f31828cb6cb.png)
![image](https://user-images.githubusercontent.com/60634446/121933149-f0e37800-cd02-11eb-9a6b-50fc36fab1df.png)

It looks like the /runtime/singularity.py file is looking for a particular list of cluster names (_get function line 951-969) and since I am creating a new test name (has not existed before), I'm assuming that singularity.py can't find the test in this list. However, I am not completely sure if this is the cause or how to go about fixing the issue.

**Comment by Snell1224** [comment]
@narategithub do you happen to know what could be going on here? Delved into the code today but could not figure out the issue yet.

**Comment by narategithub** [comment]
@Snell1224  `runtime/singularity.py` does not have a list of all test scripts. It will lookup/create cluster of containers informed by your test script. And, when you `get(create=True)`, it will create the cluster of containers if lookup failed.

The error suggested that `/home/user/db/user-agg_test_sw...` does not exist. I'm guessing that `/home/user` was not NFS mounted, making a remote host not able to create a container. The `db` directory is a drop box to/from containers and is required to be NFS mounted so that contents in that directory are available to all containers.

**Comment by Snell1224** [comment]
@narategithub Ah okay I got it working now. You were correct, the VMs were not NFS mounted. I will close this issue now, thank you!
